#!/usr/bin/env zx

import _fs from "fs";
import { chalk } from "zx";

const fs = _fs.promises;

/**
 * @description This function is subduquered according to the file name generated by `npm run generate your filename`,
 * then automatically injects imported import export in src/components/index.js.
 *
 * @param { string } directoryName
 * @returns { void }
 */
const additionalEntryContent = async (directoryName) => {
  const originalFile = "./src/components/index.ts";

  // Read original file content
  const entryFileContent = await fs.readFile(originalFile, "utf-8");

  // Additional content
  fs.writeFile(
    originalFile,
    entryFileContent.concat(
      `
export type { I${directoryName}Props } './${directoryName}';
export { default as ${directoryName} } from "./${directoryName}";\n`
    )
  );

  console.log(
    chalk.green(`Successfully additional content in: ${originalFile}`)
  );
};

export default additionalEntryContent;
